import React from 'react';

/**
 * Watermark component for free/preview tiers and exports.
 *
 * Two modes:
 *   - "overlay" — full-viewport repeating diagonal watermark (for demo mode)
 *   - "badge"   — small bottom-right badge (for screenshots/exports)
 *
 * Props:
 *   mode     — 'overlay' | 'badge' (default 'overlay')
 *   text     — watermark text (default 'Labno Labs')
 *   opacity  — number (default 0.08 for overlay, 0.3 for badge)
 *   isDemo   — boolean, when true uses demo-specific text and adds privacy overlay
 */
const Watermark = ({ mode = 'overlay', text = 'Labno Labs', opacity, isDemo = false }) => {
  const displayText = isDemo ? 'DEMO — labno-labs-center.vercel.app' : text;
  if (mode === 'badge') {
    const badgeOpacity = opacity ?? 0.3;
    return (
      <div
        style={{
          position: 'fixed',
          bottom: 16,
          right: 16,
          zIndex: 9998,
          opacity: badgeOpacity,
          pointerEvents: 'none',
          fontSize: '0.68rem',
          fontWeight: 600,
          color: '#2e2c2a',
          background: 'rgba(255,255,255,0.7)',
          border: '1px solid rgba(0,0,0,0.08)',
          borderRadius: 8,
          padding: '4px 10px',
          backdropFilter: 'blur(4px)',
          letterSpacing: '0.02em',
          fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        }}
      >
        Built with {displayText}
      </div>
    );
  }

  // Overlay mode — repeating diagonal watermark across the viewport
  const overlayOpacity = opacity ?? 0.08;
  return (
    <>
      {isDemo && (
        <div
          style={{
            position: 'fixed',
            inset: 0,
            zIndex: 9997,
            pointerEvents: 'none',
            background: 'rgba(255,255,255,0.04)',
            backdropFilter: 'blur(0.6px)',
          }}
        />
      )}
      <div
        style={{
          position: 'fixed',
          inset: 0,
          zIndex: 9998,
          pointerEvents: 'none',
          overflow: 'hidden',
          opacity: overlayOpacity,
        }}
      >
        <div
          style={{
            position: 'absolute',
            top: '50%',
            left: '50%',
            width: '200vmax',
            transform: 'translate(-50%, -50%) rotate(-30deg)',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: '80px',
          }}
        >
          {Array.from({ length: 12 }).map((_, row) => (
            <div
              key={row}
              style={{
                display: 'flex',
                gap: '120px',
                whiteSpace: 'nowrap',
              }}
            >
              {Array.from({ length: 8 }).map((_, col) => (
                <span
                  key={col}
                  style={{
                    fontSize: isDemo ? '1.8rem' : '3rem',
                    fontWeight: 800,
                    color: '#2e2c2a',
                    userSelect: 'none',
                    letterSpacing: '0.04em',
                    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
                  }}
                >
                  {displayText}
                </span>
              ))}
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

/**
 * Returns the HTML string for a watermark badge, suitable for appending
 * to exported HTML files.
 */
export const watermarkBadgeHtml = (text = 'Labno Labs') => `
<div style="position:fixed;bottom:16px;right:16px;z-index:9998;opacity:0.3;pointer-events:none;font-size:0.68rem;font-weight:600;color:#2e2c2a;background:rgba(255,255,255,0.7);border:1px solid rgba(0,0,0,0.08);border-radius:8px;padding:4px 10px;backdrop-filter:blur(4px);letter-spacing:0.02em;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  Built with ${text}
</div>`;

/**
 * Returns a markdown footer line for template exports.
 */
export const watermarkFooterText = (text = 'Labno Labs') =>
  `\n\n---\n_Generated by ${text}_\n`;

export default Watermark;
